project:
  type: website
  output-dir: docs

website:
  title: "C-Cubed Workshops"
  page-navigation: true
  navbar:
    left:
      - text: Data Visualization with ggplot2
        href: Worked-Through-Example.qmd
      - text: Public Health DSDE at Yale
        href: https://ysph.yale.edu/public-health-research-and-practice/research-centers-and-initiatives/public-health-data-science-and-data-equity/
        target: _blank

format:
  html:
    theme: sandstone
    toc: true



